# Generated by Django 4.1.7 on 2023-04-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='link_pay',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_status',
            field=models.CharField(choices=[('created', 'создан'), ('confirmed', 'подтвержден'), ('rejected', 'отклонен')], default='created', max_length=50, verbose_name='Статус оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tinkoff_payment_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID платежа'),
        ),
    ]
