# Generated by Django 4.1.7 on 2023-04-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='datetime_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=1000, verbose_name='Стоимость курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='datetime_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления'),
        ),
    ]
